CREATE TABLE `tbl_form_allcare_ros` (
	`id` int(11) NOT NULL auto_increment,
	`pid` int(11) NOT NULL,
	`activity` int(11) NOT NULL default '1',
	`date` datetime default NULL,
        `constitutional` varchar(15) NOT NULL ,
        `constitutional_text` LONGTEXT NOT NULL,
	`weight_change` varchar(3) NOT NULL default 'N/A',
	`weakness` varchar(3) NOT NULL default 'N/A',
	`fatigue` varchar(3) NOT NULL default 'N/A',
	`anorexia` varchar(3) NOT NULL default 'N/A',
	`fever` varchar(3) NOT NULL default 'N/A',
	`chills` varchar(3) NOT NULL default 'N/A',
	`night_sweats` varchar(3) NOT NULL default 'N/A',
	`insomnia` varchar(3) NOT NULL default 'N/A',
	`irritability` varchar(3) NOT NULL default 'N/A',
	`heat_or_cold` varchar(3) NOT NULL default 'N/A',
	`intolerance` varchar(3) NOT NULL default 'N/A',
        `appetite` varchar(3) NOT NULL default 'N/A',
        `eyes` varchar(15) NOT NULL ,
        `eyes_text` LONGTEXT NOT NULL,
	`change_in_vision` varchar(3) NOT NULL default 'N/A',
	`glaucoma_history` varchar(3) NOT NULL default 'N/A',
	`eye_pain` varchar(3) NOT NULL default 'N/A',
	`irritation` varchar(3) NOT NULL default 'N/A',
	`redness` varchar(3) NOT NULL default 'N/A',
	`excessive_tearing` varchar(3) NOT NULL default 'N/A',
	`double_vision` varchar(3) NOT NULL default 'N/A',
	`blind_spots` varchar(3) NOT NULL default 'N/A',
	`photophobia` varchar(3) NOT NULL default 'N/A',
        `glaucoma` varchar(3) NOT NULL default 'N/A',
	`cataract` varchar(3) NOT NULL default 'N/A',
        `injury` varchar(3) NOT NULL default 'N/A',
	`ha` varchar(3) NOT NULL default 'N/A',
        `coryza` varchar(3) NOT NULL default 'N/A',
	`obstruction` varchar(3) NOT NULL default 'N/A',
        `ent` varchar(15) NOT NULL ,
        `ent_text` LONGTEXT NOT NULL,
	`hearing_loss` varchar(3) NOT NULL default 'N/A',
	`discharge` varchar(3) NOT NULL default 'N/A',
	`pain` varchar(3) NOT NULL default 'N/A',
	`vertigo` varchar(3) NOT NULL default 'N/A',
	`tinnitus` varchar(3) NOT NULL default 'N/A',
	`frequent_colds` varchar(3) NOT NULL default 'N/A',
	`sore_throat` varchar(3) NOT NULL default 'N/A',
	`sinus_problems` varchar(3) NOT NULL default 'N/A',
	`post_nasal_drip` varchar(3) NOT NULL default 'N/A',
	`nosebleed` varchar(3) NOT NULL default 'N/A',
	`snoring` varchar(3) NOT NULL default 'N/A',
	`apnea` varchar(3) NOT NULL default 'N/A',
	`bleeding_gums` varchar(3) NOT NULL default 'N/A',
	`hoarseness` varchar(3) NOT NULL default 'N/A',
        `dental_difficulties` varchar(3) NOT NULL default 'N/A',
	`dentures` varchar(3) NOT NULL default 'N/A',
        `breast` varchar(15) NOT NULL,
        `breast_text` LONGTEXT NOT NULL,
        `breast_mass` varchar(3) NOT NULL default 'N/A',
	`breast_discharge` varchar(3) NOT NULL default 'N/A',
	`biopsy` varchar(3) NOT NULL default 'N/A',
	`abnormal_mammogram` varchar(3) NOT NULL default 'N/A',
        `respiratory`  varchar(15) NOT NULL ,
        `respiratory_text` LONGTEXT NOT NULL,
	`cough` varchar(3) NOT NULL default 'N/A',
	`sputum` varchar(3) NOT NULL default 'N/A',
	`shortness_of_breath` varchar(3) NOT NULL default 'N/A',
	`wheezing` varchar(3) NOT NULL default 'N/A',
	`hemoptsyis` varchar(3) NOT NULL default 'N/A',
	`asthma` varchar(3) NOT NULL default 'N/A',
	`copd` varchar(3) NOT NULL default 'N/A',
        `cardiovascular`  varchar(15) NOT NULL ,
        `cardiovascular_text` LONGTEXT NOT NULL,
	`chest_pain` varchar(3) NOT NULL default 'N/A',
	`palpitation` varchar(3) NOT NULL default 'N/A',
	`syncope` varchar(3) NOT NULL default 'N/A',
	`pnd` varchar(3) NOT NULL default 'N/A',
	`doe` varchar(3) NOT NULL default 'N/A',
	`orthopnea` varchar(3) NOT NULL default 'N/A',
	`peripheal` varchar(3) NOT NULL default 'N/A',
	`edema` varchar(3) NOT NULL default 'N/A',
	`legpain_cramping` varchar(3) NOT NULL default 'N/A',
	`history_murmur` varchar(3) NOT NULL default 'N/A',
	`arrythmia` varchar(3) NOT NULL default 'N/A',
	`heart_problem` varchar(3) NOT NULL default 'N/A',
        `gastrointestinal` varchar(15) NOT NULL default 'N/A',
        `gastrointestinal_text`  LONGTEXT NOT NULL,
	`dysphagia` varchar(3) NOT NULL default 'N/A',
	`heartburn` varchar(3) NOT NULL default 'N/A',
	`bloating` varchar(3) NOT NULL default 'N/A',
	`belching` varchar(3) NOT NULL default 'N/A',
	`flatulence` varchar(3) NOT NULL default 'N/A',
	`nausea` varchar(3) NOT NULL default 'N/A',
	`vomiting` varchar(3) NOT NULL default 'N/A',
	`hematemesis` varchar(3) NOT NULL default 'N/A',
	`gastro_pain` varchar(3) NOT NULL default 'N/A',
	`food_intolerance` varchar(3) NOT NULL default 'N/A',
	`hepatitis` varchar(3) NOT NULL default 'N/A',
	`jaundice` varchar(3) NOT NULL default 'N/A',
	`hematochezia` varchar(3) NOT NULL default 'N/A',
	`changed_bowel` varchar(3) NOT NULL default 'N/A',
	`diarrhea` varchar(3) NOT NULL default 'N/A',
	`constipation` varchar(3) NOT NULL default 'N/A',
        `blood_in_stool` varchar(3) NOT NULL default 'N/A',
	`trouble_swallowing` varchar(3) NOT NULL default 'N/A',
        `genitourinary` varchar(15) NOT NULL ,
        `genitourinary_text`  LONGTEXT NOT NULL,
	`polyuria` varchar(3) NOT NULL default 'N/A',
	`polydypsia` varchar(3) NOT NULL default 'N/A',
	`dysuria` varchar(3) NOT NULL default 'N/A',
	`hematuria` varchar(3) NOT NULL default 'N/A',
	`frequency` varchar(3) NOT NULL default 'N/A',
	`urgency` varchar(3) NOT NULL default 'N/A',
	`incontinence` varchar(3) NOT NULL default 'N/A',
	`renal_stones` varchar(3) NOT NULL default 'N/A',
	`utis` varchar(3) NOT NULL default 'N/A',
	`blood_in_urine` varchar(3) NOT NULL default 'N/A',
	`urinary_retention` varchar(3) NOT NULL default 'N/A',
        `change_in_nature_of_urine` varchar(3) NOT NULL default 'N/A',
        `genitourinarymale` varchar(15) NOT NULL ,
        `genitourinarymale_text`  LONGTEXT NOT NULL,
        `hesitancy` varchar(3) NOT NULL default 'N/A',
	`dribbling` varchar(3) NOT NULL default 'N/A',
	`stream` varchar(3) NOT NULL default 'N/A',
	`nocturia` varchar(3) NOT NULL default 'N/A',
	`erections` varchar(3) NOT NULL default 'N/A',
	`ejaculations` varchar(3) NOT NULL default 'N/A',
        `genitourinaryfemale` varchar(15) NOT NULL ,
        `genitourinaryfemale_text`  LONGTEXT NOT NULL,
	`g` varchar(3) NOT NULL default 'N/A',
	`p` varchar(3) NOT NULL default 'N/A',
	`ap` varchar(3) NOT NULL default 'N/A',
	`lc` varchar(3) NOT NULL default 'N/A',
	`mearche` varchar(3) NOT NULL default 'N/A',
	`menopause` varchar(3) NOT NULL default 'N/A',
	`lmp` varchar(3) NOT NULL default 'N/A',
	`f_frequency` varchar(3) NOT NULL default 'N/A',
	`f_flow` varchar(3) NOT NULL default 'N/A',
	`f_symptoms` varchar(3) NOT NULL default 'N/A',
	`abnormal_hair_growth` varchar(3) NOT NULL default 'N/A',
	`f_hirsutism` varchar(3) NOT NULL default 'N/A',
        `musculoskeletal` varchar(15) NOT NULL,
        `musculoskeletal_text`  LONGTEXT NOT NULL,
	`joint_pain` varchar(3) NOT NULL default 'N/A',
	`swelling` varchar(3) NOT NULL default 'N/A',
	`m_redness` varchar(3) NOT NULL default 'N/A',
	`m_warm` varchar(3) NOT NULL default 'N/A',
	`m_stiffness` varchar(3) NOT NULL default 'N/A',
	`muscle` varchar(3) NOT NULL default 'N/A',
	`m_aches` varchar(3) NOT NULL default 'N/A',
	`fms` varchar(3) NOT NULL default 'N/A',
	`arthritis` varchar(3) NOT NULL default 'N/A',
        `gout` varchar(3) NOT NULL default 'N/A',
	`back_pain` varchar(3) NOT NULL default 'N/A',
        `range_of_motion`varchar(3) NOT NULL default 'N/A',
        `paraesthesia` varchar(3) NOT NULL default 'N/A',
`extremities` varchar(15) NOT NULL,
        `extremities_text`  LONGTEXT NOT NULL,
	`spasms` varchar(3) NOT NULL default 'N/A',
	`extreme_tremors` varchar(3) NOT NULL default 'N/A',
        `neurologic` varchar(15) NOT NULL,
        `neurologic_text`  LONGTEXT NOT NULL,
	`loc` varchar(3) NOT NULL default 'N/A',
	`seizures` varchar(3) NOT NULL default 'N/A',
	`stroke` varchar(3) NOT NULL default 'N/A',
	`tia` varchar(3) NOT NULL default 'N/A',
	`n_numbness` varchar(3) NOT NULL default 'N/A',
	`n_weakness` varchar(3) NOT NULL default 'N/A',
	`paralysis` varchar(3) NOT NULL default 'N/A',
	`intellectual_decline` varchar(3) NOT NULL default 'N/A',
	`memory_problems` varchar(3) NOT NULL default 'N/A',
	`dementia` varchar(3) NOT NULL default 'N/A',
	`n_headache` varchar(3) NOT NULL default 'N/A',
        `dizziness_vertigo` varchar(3) NOT NULL default 'N/A',
	`slurred_speech` varchar(3) NOT NULL default 'N/A',
	`tremors` varchar(3) NOT NULL default 'N/A',
	`migraines` varchar(3) NOT NULL default 'N/A',
        `skin` varchar(15) NOT NULL ,
        `skin_text`  LONGTEXT NOT NULL,
	`s_cancer` varchar(3) NOT NULL default 'N/A',
	`psoriasis` varchar(3) NOT NULL default 'N/A',
	`s_acne` varchar(3) NOT NULL default 'N/A',
	`s_other` varchar(3) NOT NULL default 'N/A',
	`s_disease` varchar(3) NOT NULL default 'N/A',
        `rashes` varchar(3) NOT NULL default 'N/A',
	`dryness` varchar(3) NOT NULL default 'N/A',
	`itching` varchar(3) NOT NULL default 'N/A',
        `psychiatric` varchar(15) NOT NULL ,
        `psychiatric_text`  LONGTEXT NOT NULL,
	`p_diagnosis` varchar(3) NOT NULL default 'N/A',
	`p_medication` varchar(3) NOT NULL default 'N/A',
	`depression` varchar(3) NOT NULL default 'N/A',
	`anxiety` varchar(3) NOT NULL default 'N/A',
	`social_difficulties` varchar(3) NOT NULL default 'N/A',
	`alcohol_drug_dependence` varchar(3) NOT NULL default 'N/A',
	`suicide_thoughts` varchar(3) NOT NULL default 'N/A',
	`use_of_antideprassants` varchar(3) NOT NULL default 'N/A',
        `thought_content` varchar(3) NOT NULL default 'N/A',
        `endocrine` varchar(15) NOT NULL ,
        `endocrine_text`  LONGTEXT NOT NULL,
        `thyroid_problems` varchar(3) NOT NULL default 'N/A',
	`diabetes` varchar(3) NOT NULL default 'N/A',
	`abnormal_blood` varchar(3) NOT NULL default 'N/A',
        `goiter` varchar(3) NOT NULL default 'N/A',
	`heat_intolerence` varchar(3) NOT NULL default 'N/A',
	`cold_intolerence` varchar(3) NOT NULL default 'N/A',
	`increased_thirst` varchar(3) NOT NULL default 'N/A',
	`excessive_sweating` varchar(3) NOT NULL default 'N/A',
	`excessive_hunger` varchar(3) NOT NULL default 'N/A',
        `hai` varchar(15) NOT NULL ,
        `hai_text`  LONGTEXT NOT NULL,
	`anemia` varchar(3) NOT NULL default 'N/A',
	`fh_blood_problems` varchar(3) NOT NULL default 'N/A',
	`bleeding_problems` varchar(3) NOT NULL default 'N/A',
	`allergies` varchar(3) NOT NULL default 'N/A',
	`frequent_illness` varchar(3) NOT NULL default 'N/A',
	`hiv` varchar(3) NOT NULL default 'N/A',
	`hai_status` varchar(3) NOT NULL default 'N/A',
        `hay_fever` varchar(3) NOT NULL default 'N/A',
	`positive_ppd` varchar(3) NOT NULL default 'N/A',
        `neck` varchar(15) NOT NULL,
        `neck_text` LONGTEXT NOT NULL,
        `stiffness` varchar(3) NOT NULL default 'N/A',
	`neck_pain` varchar(3) NOT NULL default 'N/A',
        `masses` varchar(3) NOT NULL default 'N/A',
	`tenderness` varchar(3) NOT NULL default 'N/A',
        `pending` TEXT NOT NULL,
        `finalized` TEXT NOT NULL,
        PRIMARY KEY (id)
	) ENGINE=InnoDB;

