CREATE TABLE IF NOT EXISTS `tbl_form_facetoface` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `pid` int(10) NOT NULL,
  `encounter` int(10) NOT NULL,
  `date_of_service` date NOT NULL,
  `is_home_bound` enum('Y','N') NOT NULL,
  `is_hhc_needed` enum('Y','N') NOT NULL,
  `other_physician` enum('Y','N') NOT NULL,
  `is_house_visit_needed` enum('Y','N') NOT NULL,
  `medical_condition` varchar(100) DEFAULT NULL,
  `necessary_hhs` varchar(500) DEFAULT NULL,
  `nursing` varchar(500) DEFAULT NULL,
  `physical_therapy` varchar(500) DEFAULT NULL,
  `occupational_therapy` varchar(500) DEFAULT NULL,
  `speech` varchar(500) DEFAULT NULL,
  `support_service_reason` varchar(500) DEFAULT NULL,
  `patient_homebound_reason` varchar(500) DEFAULT NULL,
  `nurse_practitioner_signature` varchar(100) DEFAULT NULL,
  `nurse_practitioner_signature_date` date DEFAULT NULL,
  `physician_signature` varchar(100) DEFAULT NULL,
  `printed_name` varchar(100) DEFAULT NULL,
  `printed_name_date` date DEFAULT NULL,
  `created_date` datetime NOT NULL,
  `updated_date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
