<?php

$links = array('<a href="sample01">Sample01 - How to login to GroupDocs using the API</a>',
               '<a href="sample02">Sample02 - How to list files within GroupDocs Storage using the Storage API</a>',
               '<a href="sample03">Sample03 - How to upload a file to GroupDocs using the Storage API</a>',
               '<a href="sample04">Sample04 - How to download a file from GroupDocs Storage using the Storage API</a>',
               '<a href="sample05">Sample05 - How to copy / move a file using the GroupDocs Storage API</a>',
               '<a href="sample06">Sample06 - How to add a Signature to a document in GroupDocs Signature</a>',
               '<a href="sample07">Sample07 - How to create a list of thumbnails for a document</a>',
               '<a href="sample08">Sample08 - How to return a URL representing a single page of a Document</a>',
               '<a href="sample09">Sample09 - How to generate an embedded Viewer URL for a Document</a>',
               '<a href="sample10">Sample10 - How to share a document to other users</a>',
               '<a href="/sample11">Sample11 - How programmatically create and post an annotation into document. How to delete the annotation</a>',
               '<a href="/sample12">Sample12 - How to list all annotations from document</a>',
               '<a href="/sample13">Sample13 - How to add collaborator to doc with annotations</a>',
               '<a href="/sample14">Sample14 - How to check the list of shares for a folder</a>',
               '<a href="/sample15">Sample15 - How to check the number of document\'s views</a>',
               '<a href="/sample16">Sample16 - How to insert Assembly questionary into webpage</a>',
               '<a href="/sample17">Sample17 - How to upload a file into the storage and compress it into zip archive</a>',
               '<a href="/sample18">Sample18 - How to convert Doc to Docx, Docx to Doc, Docx to PDF and PPT to PDF</a>',
               '<a href="/sample19">Sample19 - How to Compare documents using PHP SDK</a>',
               '<a href="/sample20">Sample20 - How to Get Compare Change list for document using PHP SDK</a>',
               '<a href="/sample21">Sample21 - How to Create and Upload Envelop to GroupDocs account using PHP SDK</a>',
               '<a href="/sample22">Sample22 - This sample will show how create or update user and add him to collaborators using PHP SDK</a>',
               '<a href="/sample23">Sample23 - How to  View Document pages as images using PHP SDK</a>',
               '<a href="sample24">Sample24 - How to upload file from URL to GroupDocs account using PHP SDK</a>',
               '<a href="sample25">Sample25 - How to convert DOCX with template fields file into PDF using PHP SDK</a>',
               '<a href="sample26">Sample26 - How to use login method in the API</a>',
               '<a href="sample27">Sample27 - How to create your own questionary using forms and show the result document using PHP SDK</a>',
               '<a href="sample28">Sample28 - How to delete all annotations from document</a>',
               '<a href="sample29">Sample29 - How to use Filepicker.io to upload document and get it\'s URL</a>',
               '<a href="sample30">Sample30 - How to delete file from GroupDocs Storage using PHP SDK</a>',
               '<a href="sample31">Sample31 - How to dinamically create Signature Form using data from HTM form</a>');
F3::set('links', $links);

?>
